/**
 * Canonical site identity, shared by metadata, the sitemap, robots, and JSON-LD.
 *
 * `NEXT_PUBLIC_SITE_URL` is set in the Vercel project; the fallback is the
 * production domain so local builds and previews still resolve absolute URLs.
 * Any trailing slash is trimmed so callers can safely do `${SITE_URL}/path`.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.seojaestory.app").replace(/\/+$/, "");

export const SITE_NAME = "SeoJae Story";

export const SITE_DESCRIPTION =
  "Learn English or Korean through short stories, with instant translations, listening practice, vocabulary flashcards, and gentle writing feedback.";

/**
 * The default social share image, generated by src/app/opengraph-image.tsx.
 * The root layout and `/` pick this up from the file convention automatically;
 * routes that set their own `openGraph`/`twitter` metadata (e.g. lesson pages)
 * need to pass it through explicitly, so it lives here.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — short stories for language learners`,
};
